insert into Andy (Andy, filename, first_name) values (90704-2934, primary.clp, Deon);
insert into Andy (Andy, filename, first_name) values (09174-8356, deposit_invoice_shilling.osf, Elda);
insert into Andy (Andy, filename, first_name) values (99466-1901, withdrawal_interactive.aw, Monty);
insert into Andy (Andy, filename, first_name) values (18476, methodologies_tala_multi_byte.otp, Tad);
insert into Andy (Andy, filename, first_name) values (79909, cross_group.fxpl, Toney);
insert into Andy (Andy, filename, first_name) values (29553-8172, tasty.les, Arden);
insert into Andy (Andy, filename, first_name) values (56083-1768, dinar.nb, Cordell);
insert into Andy (Andy, filename, first_name) values (28240-8432, rupee_invoice.appcache, Aryanna);
insert into Andy (Andy, filename, first_name) values (10669, colombia_synthesize_national.nnw, Roberto);
insert into Andy (Andy, filename, first_name) values (26327, springs_creative.uvvp, Bernhard);
insert into Andy (Andy, filename, first_name) values (22497-7182, cambridgeshire.rms, Aida);
insert into Andy (Andy, filename, first_name) values (17612-7932, gold.gnumeric, Skye);
insert into Andy (Andy, filename, first_name) values (24625-9847, methodologies.spl, Lysanne);
insert into Andy (Andy, filename, first_name) values (48937, optimized_redundant.woff, Allan);
insert into Andy (Andy, filename, first_name) values (95016-2155, nebraska.ppt, Skyla);
insert into Andy (Andy, filename, first_name) values (70743-4595, village_rss_senior.rcprofile, Merritt);
insert into Andy (Andy, filename, first_name) values (37787, persistent.fm, Anastasia);
insert into Andy (Andy, filename, first_name) values (30817-7102, withdrawal_wireless_intelligent.xar, Trevor);
insert into Andy (Andy, filename, first_name) values (99053-8458, parsing_stravenue_architect.mxu, Henriette);
insert into Andy (Andy, filename, first_name) values (85988, buckinghamshire_vermont_wireless.mcd, Broderick);
insert into Andy (Andy, filename, first_name) values (33063-1333, wisconsin_advanced.fh4, Mittie);
insert into Andy (Andy, filename, first_name) values (30040, kentucky_supply_chains_extension.ivu, Bianka);
insert into Andy (Andy, filename, first_name) values (62600, avon_networks.cdmio, Bennie);
insert into Andy (Andy, filename, first_name) values (03911, minnesota.mathml, Leon);
insert into Andy (Andy, filename, first_name) values (27809, programming_tan.aam, Victoria);
insert into Andy (Andy, filename, first_name) values (28058-5721, rich.sldm, Efren);
insert into Andy (Andy, filename, first_name) values (47576, compressing_jbod.7z, Elliott);
insert into Andy (Andy, filename, first_name) values (29891-8478, ohio_practical.cdmio, Jordane);
insert into Andy (Andy, filename, first_name) values (16619, com_automotive_metal.atc, Adolph);
insert into Andy (Andy, filename, first_name) values (99263-5028, solution_oriented_personal.mpga, Ali);
insert into Andy (Andy, filename, first_name) values (45232, modular.lnk, Nikki);
insert into Andy (Andy, filename, first_name) values (27793-2597, cambridgeshire_maximized.wqd, Ladarius);
insert into Andy (Andy, filename, first_name) values (49029, stable.nns, Nicholaus);
insert into Andy (Andy, filename, first_name) values (00171-5889, intelligent.gslides, Caleigh);
insert into Andy (Andy, filename, first_name) values (35227-3406, rubber_systems.dwf, Meghan);
insert into Andy (Andy, filename, first_name) values (48709, ethiopia_fish.std, Jace);
insert into Andy (Andy, filename, first_name) values (53099-3495, bluetooth_small_generate.distz, Aryanna);
insert into Andy (Andy, filename, first_name) values (87786, fundamental_challenge.mpe, Brooklyn);
insert into Andy (Andy, filename, first_name) values (40291-6729, shoes.x3dbz, Dulce);
insert into Andy (Andy, filename, first_name) values (56858, buckinghamshire.mks, Bethel);
insert into Andy (Andy, filename, first_name) values (41075, savings.rar, Telly);
insert into Andy (Andy, filename, first_name) values (24123, leading_edge_e_services_1080p.cww, Rex);
insert into Andy (Andy, filename, first_name) values (46793-4203, exploit_concrete.h, Hadley);

insert into User (first_name, last_name) values (Milo, Greenfelder);
insert into User (first_name, last_name) values (Waylon, McCullough);
insert into User (first_name, last_name) values (Everardo, Kemmer);
insert into User (first_name, last_name) values (Dax, Purdy);
insert into User (first_name, last_name) values (Dayne, Tremblay);
insert into User (first_name, last_name) values (Jessyca, McLaughlin);
insert into User (first_name, last_name) values (Aiyana, Dooley);
insert into User (first_name, last_name) values (Kayleigh, Moore);
insert into User (first_name, last_name) values (Emelie, Berge);
insert into User (first_name, last_name) values (Ryley, Hoppe);
insert into User (first_name, last_name) values (Charity, Corwin);
insert into User (first_name, last_name) values (Mozelle, Block);
insert into User (first_name, last_name) values (Elvis, Bechtelar);
insert into User (first_name, last_name) values (Kaylin, Moore);
insert into User (first_name, last_name) values (Agustin, Dicki);
insert into User (first_name, last_name) values (Michele, Turner);
insert into User (first_name, last_name) values (Emelie, Medhurst);
insert into User (first_name, last_name) values (Holly, Dare);
insert into User (first_name, last_name) values (Rey, Rempel);
insert into User (first_name, last_name) values (Harry, Schroeder);
insert into User (first_name, last_name) values (Oscar, Klocko);
insert into User (first_name, last_name) values (Mary, Pfeffer);
insert into User (first_name, last_name) values (Diego, Schiller);
insert into User (first_name, last_name) values (Chanelle, Steuber);
insert into User (first_name, last_name) values (Tremayne, Sipes);
insert into User (first_name, last_name) values (Wilhelmine, Heller);
insert into User (first_name, last_name) values (Jonatan, Kautzer);
insert into User (first_name, last_name) values (Patsy, Treutel);
insert into User (first_name, last_name) values (Koby, Kertzmann);
insert into User (first_name, last_name) values (Marianne, Simonis);
insert into User (first_name, last_name) values (Felix, Kling);
insert into User (first_name, last_name) values (Anibal, Gutmann);
insert into User (first_name, last_name) values (Everett, Hegmann);
insert into User (first_name, last_name) values (Ali, Wunsch);
insert into User (first_name, last_name) values (Margot, Bergstrom);
insert into User (first_name, last_name) values (Karen, Ankunding);
insert into User (first_name, last_name) values (Heidi, Hills);
insert into User (first_name, last_name) values (Vella, Mayert);
insert into User (first_name, last_name) values (Connie, Gerlach);
insert into User (first_name, last_name) values (Bertram, Senger);
insert into User (first_name, last_name) values (Kayley, Weissnat);
insert into User (first_name, last_name) values (Zella, Schuppe);
insert into User (first_name, last_name) values (Ezequiel, Simonis);

